
substitutions:
  # Pin definitions
  i2c_id: internal_i2c
  reset_pin:     
    tca9555: ioexp
    number: 7 # EXIO7 
    inverted: true
  camera_data_pins: [GPIO2, GPIO17, GPIO18, GPIO39, GPIO45, GPIO46, GPIO47, GPIO48]
  camera_vsync_pin: GPIO21
  camera_href_pin: GPIO1
  camera_pclk_pin: GPIO44
  camera_xclk_pin: GPIO43  #External clock
  camera_select_pin:
      tca9555: ioexp
      number: 6 #EXIO6 
  camera_power_pin:
      tca9555: ioexp
      number: 5 #EXIO5
      inverted: true
  camera_max_framerate: '15fps'
  camera_jpeg_quality_index: '0'
  camera_jpeg_quality: '10'
  camera_resolution_index: '0'
  camera_vertical_flip: 'true'
  camera_horizontal_mirror: 'true'
  camera_rotate_180: 'true'
  camera_contrast: '0'
  camera_brightness: '0'
  camera_saturation: '0'
  camera_special_effect: 'none'
  camera_aec_mode: 'auto'
  camera_aec2: 'false'
  camera_ae_level: '0'
  camera_ae_enable: 'true'
  camera_aec_value: '300'
  camera_agc_mode: 'auto'
  camera_agc_value: '0'
  camera_agc_ceiling: '2x'
  camera_white_balance: 'auto'

  #TODO: make HA switches
  camera_xclk_frequency: 12MHz
  camera_idle_framerate: 0.1fps

# Camera configuration
esp32_camera:
  name: "ESP32 Camera"
  id: seeed_camera
  data_pins: $camera_data_pins
  vsync_pin: $camera_vsync_pin
  href_pin: $camera_href_pin
  pixel_clock_pin: $camera_pclk_pin
  external_clock: 
    pin: $camera_xclk_pin
    frequency: $camera_xclk_frequency #12MHz
  i2c_id: $i2c_id
#  power_down_pin: ${camera_power_pin}

  #frame settings  
  max_framerate: ${camera_max_framerate}
  idle_framerate: ${camera_idle_framerate} #0.1fps #default
  
  #Image Settings
  resolution: 1280X1024
  frame_buffer_location: PSRAM
  frame_buffer_count: 2
  jpeg_quality: ${camera_jpeg_quality}
  vertical_flip: ${camera_vertical_flip}
  horizontal_mirror: ${camera_horizontal_mirror}
  brightness: ${camera_brightness}
  contrast: ${camera_contrast}
  saturation: ${camera_saturation}
  special_effect: ${camera_special_effect}

  #Exposure settings
  aec_mode: ${camera_aec_mode}
  aec2: ${camera_aec2}
  ae_level: ${camera_ae_level}
  aec_value: ${camera_ae_level}
  
  #Sensor gain settings
  agc_mode: ${camera_aec_mode}
  agc_gain_ceiling: ${camera_agc_ceiling}
  agc_value: ${camera_agc_value}  
  
  #White balance settings
  wb_mode: ${camera_white_balance}

globals:
  - id: defer_camera_update
    type: bool
    restore_value: False
    initial_value: 'false'
  - id: camera_power_save
    type: bool
    restore_value: True
    initial_value: 'true'
  - id: camera_select_save
    type: bool
    restore_value: True
    initial_value: 'true'

esphome:
  on_boot:
    - priority: -100
      then:
          # If the user disables power and de-selects the camera, when the
          # device restarts the camera would fail to initialize which can't
          # be corrected without another restart.  To get around this,
          # both power and select are always enabled at boot then after everything
          # is initialized, they're disabled if needed.  This allows the user to
          # turn them back on again without needing to restart.
        - switch.control:
            id: camera_power_switch
            state: !lambda return id(camera_power_save);
        - switch.control:
            id: camera_select_switch
            state: !lambda return id(camera_select_save);

select:
    # Camera resolution can't be changed on the fly because the underlying
    # camera code sets up the frame buffer only once during setup and that's
    # dependent on frame size.
  - platform: template
    name: "Camera Resolution (restart required)"
    id: camera_resolution_select
    icon: "mdi:aspect-ratio"
    optimistic: true
    restore_value: true
    disabled_by_default: true
    options: ["QVGA (320x240)", "VGA (640x480)", "SVGA (800x600)", "XGA (1024x768)", "UXGA (1600x1200)"]
    on_value:
      then:
        - lambda: |-
            // This code does nothing unless run before setup has run.
            // 'i' is set to the index of the currently selected option.
            esp32_camera::ESP32CameraFrameSize fs[] = {
              esp32_camera::ESP32_CAMERA_SIZE_320X240,
              esp32_camera::ESP32_CAMERA_SIZE_640X480,
              esp32_camera::ESP32_CAMERA_SIZE_800X600,
              esp32_camera::ESP32_CAMERA_SIZE_1024X768,
              esp32_camera::ESP32_CAMERA_SIZE_1600X1200
            };
            id(seeed_camera).set_frame_size(fs[i]);

    # Unlike resolution, quality can be set on the fly.
  - platform: template
    name: "Camera Quality"
    id: camera_jpeg_quality_select
    icon: "mdi:image-size-select-large"
    optimistic: true
    restore_value: true
    disabled_by_default: true
    options: ["Best (10)", "Good (15)", "Medium (25)", "Low (40)", "Fastest (63)"]
    on_value:
      then:
        - lambda: |-
            // 'i' is set to the index of the currently selected option.
            int qa[] = { 10, 15, 25, 40, 63 };
            id(seeed_camera).set_jpeg_quality(qa[i]);
            // esp32_camera doesn't include jpeg quality in update_camera_parameters. :(
            sensor_t *s = esp_camera_sensor_get();
            if (s != nullptr) {
              s->set_quality(s, qa[i]);
            }

  - platform: template
    name: "Camera AGC Ceiling"
    id: camera_agc_gain_select
    icon: "mdi:image-size-select-large"
    optimistic: true
    restore_value: true
    disabled_by_default: true
    options: ["2x", "4x", "8x", "16x", "32x", "64x", "128x" ]
    on_value:
      then:
        - lambda: |-
            // 'i' is set to the index of the currently selected option.
            esp32_camera::ESP32AgcGainCeiling agc[] = {
              esp32_camera::ESP32_GAINCEILING_2X,
              esp32_camera::ESP32_GAINCEILING_4X,
              esp32_camera::ESP32_GAINCEILING_8X,
              esp32_camera::ESP32_GAINCEILING_16X,
              esp32_camera::ESP32_GAINCEILING_32X,
              esp32_camera::ESP32_GAINCEILING_64X,
              esp32_camera::ESP32_GAINCEILING_128X,
            };
            id(seeed_camera).set_agc_gain_ceiling(agc[i]);
            if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

switch:
    # We need to maintain our own restore state for both select and power
    # because they both have to be ON before the camera is initialized
    # then turned off afterwards if the user has turned them off explicitly.
    # This is also why we need a separate template and gpio switch for each.
  - platform: template
    name: "Camera Select"
    id: camera_select_switch
    optimistic: True
    disabled_by_default: true
    restore_mode: DISABLED
    on_state:
      - lambda: |-
          id(camera_select_gpio).control(x);
          id(camera_select_save) = x;

  - platform: gpio
    pin: ${camera_select_pin}
    id: camera_select_gpio
    restore_mode: ALWAYS_ON
    internal: True

  - platform: template
    name: "Camera Power"
    id: camera_power_switch
    optimistic: True
    disabled_by_default: true
    restore_mode: DISABLED
    on_state:
      - lambda: |-
          id(camera_power_gpio).control(x);
          id(camera_power_save) = x;
  
  - platform: gpio
    pin: ${camera_power_pin}
    id: camera_power_gpio
    restore_mode: ALWAYS_ON
    internal: True

  - platform: template
    name: "Camera Rotate 180°"
    id: camera_rotation_switch
    icon: "mdi:rotate-3d-variant"
    disabled_by_default: true
    restore_mode: RESTORE_DEFAULT_OFF
    optimistic: True
    on_state:
      - lambda: |-
          id(seeed_camera).set_horizontal_mirror(x);
          id(seeed_camera).set_vertical_flip(x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera AEC"
    id: camera_aec_switch
    icon: "mdi:brightness-7"
    restore_mode: RESTORE_DEFAULT_ON
    disabled_by_default: true
    optimistic: True
    on_state:
      - lambda: |-
          id(seeed_camera).set_aec_mode(x ? esp32_camera::ESP32_GC_MODE_AUTO : esp32_camera::ESP32_GC_MODE_MANU);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera AEC2"
    id: camera_aec2_switch
    icon: "mdi:brightness-7"
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    optimistic: True
    on_state:
      - lambda: |-
          id(seeed_camera).set_aec2(x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera AGC"
    id: camera_agc_switch
    icon: "mdi:brightness-7"
    restore_mode: RESTORE_DEFAULT_ON
    disabled_by_default: true
    optimistic: True
    on_state:
      - lambda: |-
          id(seeed_camera).set_agc_mode(x ? esp32_camera::ESP32_GC_MODE_AUTO : esp32_camera::ESP32_GC_MODE_MANU);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera Test Pattern"
    id: camera_test_pattern_switch
    icon: "mdi:brightness-7"
    restore_mode: RESTORE_DEFAULT_OFF
    disabled_by_default: true
    optimistic: True
    on_state:
      - lambda: |-
          id(seeed_camera).set_test_pattern(x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

number:
  - platform: template
    name: "Camera AEC +-"
    id: camera_ae_level_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 0
    min_value: -2
    max_value: 2
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_ae_level((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera AGC +-"
    id: camera_agc_value_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 0
    min_value: 0
    max_value: 30
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_agc_value((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera Brightness"
    id: camera_brightness_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 0
    min_value: -2
    max_value: 2
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_brightness((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera Contrast"
    id: camera_contrast_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 0
    min_value: -2
    max_value: 2
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_contrast((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera Saturation"
    id: camera_saturation_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 0
    min_value: -2
    max_value: 2
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_saturation((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

  - platform: template
    name: "Camera ISO"
    id: camera_aec_value_number
    icon: "mdi:brightness-7"
    optimistic: true
    disabled_by_default: true
    restore_value: true
    initial_value: 300
    min_value: 0
    max_value: 1200
    step: 1
    mode: slider
    set_action:
      - lambda: |-
          id(seeed_camera).set_aec_value((int)x);
          if (!id(defer_camera_update) && esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();

button:
  - platform: template
    name: "Camera Settings Reset"
    id: reset_camera_settings
    device_class: restart
    disabled_by_default: true
    on_press:
      - lambda: id(defer_camera_update) = true;
      - select.set_index:
          id: camera_resolution_select
          index: 0
      - select.set_index:
          id: camera_jpeg_quality_select
          index: 2
      - select.set_index:
          id: camera_agc_gain_select
          index: 0
      - switch.turn_off: camera_rotation_switch
      - switch.turn_on: camera_aec_switch
      - switch.turn_on: camera_agc_switch
      - switch.turn_off: camera_test_pattern_switch
      - number.set:
          id: camera_ae_level_number
          value: 0
      - number.set:
          id: camera_aec_value_number
          value: 300
      - number.set:
          id: camera_agc_value_number
          value: 0
      - number.set:
          id: camera_brightness_number
          value: 0
      - number.set:
          id: camera_contrast_number
          value: 0
      - number.set:
          id: camera_saturation_number
          value: 0
      - lambda: |-
          if (esp_camera_sensor_get() != nullptr) id(seeed_camera).update_camera_parameters();
          id(defer_camera_update) = false;

